### ISSUE TITLE
Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by philpott** [iubenda/gtm-cookie-solution#1]
https://github.com/iubenda/gtm-cookie-solution/blob/9030111ec795aa6a3ac6121f3af1a982838be6ee/template.tpl#L242

When reviewing your template we've noticed that the setDefaultConsentState call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

**Comment by matita** [comment]
Thanks @philpott! We'll update the code to support that.

**Comment by giniyat202** [comment]
@philpott We have added the `wait_for_update` option.
